name: kunime
description: "Watch anime for free."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  random_avatar: ^0.0.8
  avatar_better: ^1.0.1
  font_awesome_flutter: ^10.11.0
  card_swiper: ^3.0.1
  http: ^1.5.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  get: ^4.7.2
  flutter_dotenv: ^6.0.0
  toasty_box: ^1.0.4
  go_router: ^17.0.0
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Coolvetica
      fonts:
        - asset: assets/fonts/coolvetica.otf
    - family: CreatoDisplay
      fonts:
        - asset: assets/fonts/creatodisplay-regular.otf
        - asset: assets/fonts/creatodisplay-bold.otf
          weight: 700
